/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Juego.Vista.Estado;

import Juego.Vista.Ventana;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Lewis
 */
public class Instrucciones extends javax.swing.JPanel {

    /**
     * Creates new form Instrucciones
     */
    public Instrucciones(final Ventana ventana) {
        initComponents();

        jButtonRegresar.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                ventana.setContentPane("Menu");
            }
        });
        jButtonSalir.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                ventana.salir();
            }
        });
    }
    
    public void enter() {
        jButtonRegresar.doClick();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonRegresar = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jScrollPaneInstrucciones = new javax.swing.JScrollPane();
        jTextAreaInstrucciones = new javax.swing.JTextArea();
        jTextAreaInstrucciones.setLineWrap(true);
        jTextAreaInstrucciones.setWrapStyleWord(false);
        jTextAreaInstrucciones.setEditable(false);
        jLabelFondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-Back.png"))); // NOI18N
        jButtonRegresar.setBorderPainted(false);
        jButtonRegresar.setContentAreaFilled(false);
        jButtonRegresar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonRegresar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-Back-Press.png"))); // NOI18N
        jButtonRegresar.setRequestFocusEnabled(false);
        jButtonRegresar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-Back-Rollover.png"))); // NOI18N
        add(jButtonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 580, 180, -1));

        jButtonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-Cancel.png"))); // NOI18N
        jButtonSalir.setBorderPainted(false);
        jButtonSalir.setContentAreaFilled(false);
        jButtonSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSalir.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-Cancel-Press.png"))); // NOI18N
        jButtonSalir.setRequestFocusEnabled(false);
        jButtonSalir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-Cancel-Rollover.png"))); // NOI18N
        add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 10, -1, -1));

        jScrollPaneInstrucciones.setBorder(null);
        jScrollPaneInstrucciones.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPaneInstrucciones.setOpaque(false);

        jTextAreaInstrucciones.setEditable(false);
        jTextAreaInstrucciones.setColumns(20);
        jTextAreaInstrucciones.setFont(Ventana.font);
        jTextAreaInstrucciones.setForeground(new java.awt.Color(255, 255, 255));
        jTextAreaInstrucciones.setLineWrap(true);
        jTextAreaInstrucciones.setRows(5);
        jTextAreaInstrucciones.setText("Arriba: W\nAbajo: S\nIzquierda: A\nDerecha: D\nCorrer: SHIFT\nRecoger: E\nAtacar: ESPACIO\nInventario: I\nPausa: ESCAPE\nComprar: B\nDebug: F1");
        jTextAreaInstrucciones.setWrapStyleWord(true);
        jTextAreaInstrucciones.setBorder(null);
        jTextAreaInstrucciones.setOpaque(false);
        jScrollPaneInstrucciones.setViewportView(jTextAreaInstrucciones);
        jScrollPaneInstrucciones.getViewport().setOpaque(false);

        add(jScrollPaneInstrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, 280, 460));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Fondo-Opaco.png"))); // NOI18N
        jLabelFondo.setText("jLabel5");
        add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JScrollPane jScrollPaneInstrucciones;
    private javax.swing.JTextArea jTextAreaInstrucciones;
    // End of variables declaration//GEN-END:variables
}
