/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Juego.Vista.Estado;

import Juego.Vista.Ventana;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Lewis
 */
public class Menu extends javax.swing.JPanel {

    /**
     * Creates new form Menu
     */
    public Menu(final Ventana ventana) {
        initComponents();

        jButtonJugar.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                ventana.setContentPane("Juego");
            }
        });
        jButtonPuntajes.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                ventana.setContentPane("Puntajes");
            }
        });
        jButtonInstrucciones.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                ventana.setContentPane("Instrucciones");
            }
        });
        jButtonSalir.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                ventana.salir();
            }
        });
        jButtonCerrarSesion.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                ventana.logOut();
            }
        });
    }
    
    public void enter() {
        jButtonJugar.doClick();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCerrarSesion = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jButtonJugar = new javax.swing.JButton();
        jButtonInstrucciones = new javax.swing.JButton();
        jButtonPuntajes = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonCerrarSesion.setFont(Ventana.font);
        jButtonCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-1.png"))); // NOI18N
        jButtonCerrarSesion.setText("Log Out");
        jButtonCerrarSesion.setBorderPainted(false);
        jButtonCerrarSesion.setContentAreaFilled(false);
        jButtonCerrarSesion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCerrarSesion.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-1-Press.png"))); // NOI18N
        jButtonCerrarSesion.setRequestFocusEnabled(false);
        jButtonCerrarSesion.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-1-Rollover.png"))); // NOI18N
        add(jButtonCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, -1));

        jButtonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-Cancel.png"))); // NOI18N
        jButtonSalir.setBorderPainted(false);
        jButtonSalir.setContentAreaFilled(false);
        jButtonSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSalir.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-Cancel-Press.png"))); // NOI18N
        jButtonSalir.setRequestFocusEnabled(false);
        jButtonSalir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-Cancel-Rollover.png"))); // NOI18N
        add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 10, -1, -1));

        jButtonJugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-Play.png"))); // NOI18N
        jButtonJugar.setBorderPainted(false);
        jButtonJugar.setContentAreaFilled(false);
        jButtonJugar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonJugar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-Play-Press.png"))); // NOI18N
        jButtonJugar.setRequestFocusEnabled(false);
        jButtonJugar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-Play-Rollover.png"))); // NOI18N
        add(jButtonJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 400, 180, -1));

        jButtonInstrucciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-Options.png"))); // NOI18N
        jButtonInstrucciones.setBorderPainted(false);
        jButtonInstrucciones.setContentAreaFilled(false);
        jButtonInstrucciones.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonInstrucciones.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-Options-Press.png"))); // NOI18N
        jButtonInstrucciones.setRequestFocusEnabled(false);
        jButtonInstrucciones.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-Options-Rollover.png"))); // NOI18N
        add(jButtonInstrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 490, 180, -1));

        jButtonPuntajes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-Ranking.png"))); // NOI18N
        jButtonPuntajes.setBorderPainted(false);
        jButtonPuntajes.setContentAreaFilled(false);
        jButtonPuntajes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonPuntajes.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-Ranking-Press.png"))); // NOI18N
        jButtonPuntajes.setRequestFocusEnabled(false);
        jButtonPuntajes.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-Ranking-Rollover.png"))); // NOI18N
        add(jButtonPuntajes, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 580, 180, -1));

        jLabelTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-Menu.png"))); // NOI18N
        jLabelTitulo.setToolTipText("");
        add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, -1, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Fondo-Opaco.png"))); // NOI18N
        jLabelFondo.setText("jLabel5");
        add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCerrarSesion;
    private javax.swing.JButton jButtonInstrucciones;
    private javax.swing.JButton jButtonJugar;
    private javax.swing.JButton jButtonPuntajes;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelTitulo;
    // End of variables declaration//GEN-END:variables

}
