/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Juego.Vista.Estado;

import Juego.Vista.Ventana;
import java.awt.Color;

/**
 *
 * @author Lewis
 */
public class Opcion extends javax.swing.JDialog {

    private String text = "Text";
    
    public static final int OPCION_MESSAGE = 1;
    public static final int OPCION_YES_OR_NO = 2;
    public static boolean OPCION_YES_OR_NO_CLICKED;

    /**
     * Creates new form Opcion
     */
    private Opcion(java.awt.Frame parent, boolean modal, String text, int type) {
        super(parent, modal);
        this.text = text;
        initComponents();

        getRootPane().setOpaque(false);
        getContentPane().setBackground(new Color(0, 0, 0, 0));
        setBackground(new Color(0, 0, 0, 0));
        
        switch(type) {
            case OPCION_MESSAGE:
                jButtonNo.setVisible(false);
                jButtonYes.setVisible(false);
                jButtonOkey.setVisible(true);
                break;
            case OPCION_YES_OR_NO:
                jButtonOkey.setVisible(false);
                jButtonNo.setVisible(true);
                jButtonYes.setVisible(true);
                break;
        }

        setLocationRelativeTo(null);
    }
    
    public static void showMessage(java.awt.Frame parent, boolean modal, String text) {
        Opcion opc = new Opcion(parent, modal, text, OPCION_MESSAGE);
        opc.setVisible(true);
    }

    public static boolean showConfirm(java.awt.Frame parent, boolean modal, String text) {
        Opcion opc = new Opcion(parent, modal, text, OPCION_YES_OR_NO);
        opc.setVisible(true);
        return OPCION_YES_OR_NO_CLICKED;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonNo = new javax.swing.JButton();
        jButtonYes = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jTextArea = new javax.swing.JTextArea();
        jButtonOkey = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setFont(Ventana.font);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonNo.setFont(Ventana.font);
        jButtonNo.setForeground(new java.awt.Color(255, 255, 255));
        jButtonNo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-1.png"))); // NOI18N
        jButtonNo.setText("NO");
        jButtonNo.setBorderPainted(false);
        jButtonNo.setContentAreaFilled(false);
        jButtonNo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonNo.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-1-Press.png"))); // NOI18N
        jButtonNo.setRequestFocusEnabled(false);
        jButtonNo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-1-Rollover.png"))); // NOI18N
        jButtonNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 180, -1));

        jButtonYes.setFont(Ventana.font);
        jButtonYes.setForeground(new java.awt.Color(255, 255, 255));
        jButtonYes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-1.png"))); // NOI18N
        jButtonYes.setText("YES");
        jButtonYes.setBorderPainted(false);
        jButtonYes.setContentAreaFilled(false);
        jButtonYes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonYes.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-1-Press.png"))); // NOI18N
        jButtonYes.setRequestFocusEnabled(false);
        jButtonYes.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-1-Rollover.png"))); // NOI18N
        jButtonYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonYesActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonYes, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 180, -1));

        jButtonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-Cancel.png"))); // NOI18N
        jButtonSalir.setBorder(null);
        jButtonSalir.setBorderPainted(false);
        jButtonSalir.setContentAreaFilled(false);
        jButtonSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSalir.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-Cancel-Press.png"))); // NOI18N
        jButtonSalir.setRequestFocusEnabled(false);
        jButtonSalir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-Cancel-Rollover.png"))); // NOI18N
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        jTextArea.setEditable(false);
        jTextArea.setColumns(20);
        jTextArea.setFont(Ventana.font);
        jTextArea.setForeground(new java.awt.Color(114, 82, 127));
        jTextArea.setLineWrap(true);
        jTextArea.setRows(5);
        jTextArea.setText(text);
        jTextArea.setWrapStyleWord(true);
        jTextArea.setBorder(null);
        jTextArea.setOpaque(false);
        getContentPane().add(jTextArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 270, 80));
        jTextArea.setBackground(new Color(0, 0, 0, 0));

        jButtonOkey.setFont(Ventana.font);
        jButtonOkey.setForeground(new java.awt.Color(255, 255, 255));
        jButtonOkey.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-1.png"))); // NOI18N
        jButtonOkey.setText("OKEY");
        jButtonOkey.setBorderPainted(false);
        jButtonOkey.setContentAreaFilled(false);
        jButtonOkey.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonOkey.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-1-Press.png"))); // NOI18N
        jButtonOkey.setRequestFocusEnabled(false);
        jButtonOkey.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-1-Rollover.png"))); // NOI18N
        jButtonOkey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkeyActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonOkey, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Fondo-Morado-Small.png"))); // NOI18N
        jLabelFondo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOkeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkeyActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonOkeyActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonYesActionPerformed
        // TODO add your handling code here:
        OPCION_YES_OR_NO_CLICKED = true;
        dispose();
    }//GEN-LAST:event_jButtonYesActionPerformed

    private void jButtonNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNoActionPerformed
        // TODO add your handling code here:
        OPCION_YES_OR_NO_CLICKED = false;
        dispose();
    }//GEN-LAST:event_jButtonNoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Opcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Opcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Opcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Opcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Opcion dialog = new Opcion(new javax.swing.JFrame(), true, "Text", OPCION_MESSAGE);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNo;
    private javax.swing.JButton jButtonOkey;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonYes;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JTextArea jTextArea;
    // End of variables declaration//GEN-END:variables
}
