/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Juego.Vista.Estado;

import Juego.Vista.Ventana;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Lewis
 */
public class Presentacion extends javax.swing.JPanel {

    /**
     * Creates new form Presentacion
     */
    public Presentacion(final Ventana ventana) {        
        initComponents();

        jButtonStart.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                ventana.setContentPane("Historia");
            }
        });
        jButtonSalir.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                ventana.salir();
            }
        });        
    }
    
    public void enter() {
        jButtonStart.doClick();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonStart = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jLabelText2 = new javax.swing.JLabel();
        jLabelText1 = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-Start.png"))); // NOI18N
        jButtonStart.setBorderPainted(false);
        jButtonStart.setContentAreaFilled(false);
        jButtonStart.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonStart.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-Start-Press.png"))); // NOI18N
        jButtonStart.setRequestFocusEnabled(false);
        jButtonStart.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-Start-Rollover.png"))); // NOI18N
        add(jButtonStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 530, 180, -1));

        jButtonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-Cancel.png"))); // NOI18N
        jButtonSalir.setBorderPainted(false);
        jButtonSalir.setContentAreaFilled(false);
        jButtonSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSalir.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-Cancel-Press.png"))); // NOI18N
        jButtonSalir.setRequestFocusEnabled(false);
        jButtonSalir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-Cancel-Rollover.png"))); // NOI18N
        add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 10, -1, -1));

        jLabelText2.setFont(Ventana.font);
        jLabelText2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelText2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelText2.setText("AYÚDANOS");
        add(jLabelText2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 490, 580, 30));

        jLabelText1.setFont(Ventana.font);
        jLabelText1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelText1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelText1.setText("EL MUNDO ESTÁ EN PELIGRO!");
        add(jLabelText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 460, 580, 30));

        jLabelTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-ResidentUDO.png"))); // NOI18N
        jLabelTitulo.setToolTipText("");
        jLabelTitulo.setFocusable(false);
        jLabelTitulo.setRequestFocusEnabled(false);
        add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, -1, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Fondo-Opaco.png"))); // NOI18N
        jLabelFondo.setText("jLabel5");
        add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonStart;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelText1;
    private javax.swing.JLabel jLabelText2;
    private javax.swing.JLabel jLabelTitulo;
    // End of variables declaration//GEN-END:variables

}
