package Juego.Vista.Estado;

import Juego.Controlador.Cargador;
import Juego.Modelo.Estructura.ListaSimple;
import Juego.Modelo.Estructura.NodoListaSimple;
import Juego.Vista.Ventana;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Lewis
 */
public class Puntajes extends javax.swing.JPanel {
    
    /**
     * Creates new form Puntajes
     */
    public Puntajes(final Ventana ventana) {
        initComponents();

        jButtonRegresar.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                ventana.setContentPane("Menu");
            }
        });
        jButtonSalir.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                ventana.salir();
            }
        });
        
        ListaSimple puntajes = Cargador.puntajes("/registros/usuarios");
        NodoListaSimple nodo = puntajes.getFirstNodo();
        String texto = "";
        while(nodo != null) {
            String[] info = nodo.get().toString().split(" - ");
            texto += info[0] + "\t\t";
            texto += info[1];
            if(nodo.getNext() != null) texto += "\n";
            nodo = nodo.getNext();
        }
        jTextAreaPuntajes.setText(texto);
    }
    
    public void enter() {
        jButtonRegresar.doClick();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPanePuntajes = new javax.swing.JScrollPane();
        jTextAreaPuntajes = new javax.swing.JTextArea();
        jTextAreaPuntajes.setLineWrap(true);
        jTextAreaPuntajes.setWrapStyleWord(false);
        jTextAreaPuntajes.setEditable(false);
        jButtonSalir = new javax.swing.JButton();
        jButtonRegresar = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPanePuntajes.setBorder(null);
        jScrollPanePuntajes.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPanePuntajes.setOpaque(false);

        jTextAreaPuntajes.setEditable(false);
        jTextAreaPuntajes.setColumns(20);
        jTextAreaPuntajes.setFont(Ventana.font);
        jTextAreaPuntajes.setForeground(new java.awt.Color(255, 255, 255));
        jTextAreaPuntajes.setLineWrap(true);
        jTextAreaPuntajes.setRows(5);
        jTextAreaPuntajes.setText("Lewis 1000\nSarahis 1000");
        jTextAreaPuntajes.setWrapStyleWord(true);
        jTextAreaPuntajes.setBorder(null);
        jTextAreaPuntajes.setOpaque(false);
        jScrollPanePuntajes.setViewportView(jTextAreaPuntajes);
        jScrollPanePuntajes.getViewport().setOpaque(false);

        add(jScrollPanePuntajes, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 550, 460));

        jButtonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-Cancel.png"))); // NOI18N
        jButtonSalir.setBorderPainted(false);
        jButtonSalir.setContentAreaFilled(false);
        jButtonSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSalir.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-Cancel-Press.png"))); // NOI18N
        jButtonSalir.setRequestFocusEnabled(false);
        jButtonSalir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-Cancel-Rollover.png"))); // NOI18N
        add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 10, -1, -1));

        jButtonRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-Back.png"))); // NOI18N
        jButtonRegresar.setBorderPainted(false);
        jButtonRegresar.setContentAreaFilled(false);
        jButtonRegresar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonRegresar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-Back-Press.png"))); // NOI18N
        jButtonRegresar.setRequestFocusEnabled(false);
        jButtonRegresar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-Back-Rollover.png"))); // NOI18N
        add(jButtonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 530, 180, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Fondo-Opaco.png"))); // NOI18N
        jLabelFondo.setText("jLabel5");
        add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JScrollPane jScrollPanePuntajes;
    private javax.swing.JTextArea jTextAreaPuntajes;
    // End of variables declaration//GEN-END:variables
}
