/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Juego.Vista.Estado;

import Juego.Controlador.Cargador;
import Juego.Vista.Ventana;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Lewis
 */
public class Register extends javax.swing.JPanel {

    private Ventana ventana;

    /**
     * Creates new form Presentacion
     */
    public Register(final Ventana ventana) {
        initComponents();
        this.ventana = ventana;

        jButtonSalir.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                ventana.salir();
            }
        });
    }
    
    public void enter() {
        jButtonRegister.doClick();
    }
    
    public boolean isRecordarSesion() {
        return jCheckBoxRecordarSesion.isSelected();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxRecordarSesion = new javax.swing.JCheckBox();
        jCheckBoxMantenerSesion = new javax.swing.JCheckBox();
        jButtonRegister = new javax.swing.JButton();
        jButtonLogin = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();
        jTextFieldUser = new javax.swing.JTextField();
        jLabelUser = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTextFieldPass = new javax.swing.JTextField();
        jLabelPass = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabelFondo = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCheckBoxRecordarSesion.setFont(Ventana.font);
        jCheckBoxRecordarSesion.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxRecordarSesion.setText("Recuerdame");
        jCheckBoxRecordarSesion.setBorder(null);
        jCheckBoxRecordarSesion.setFocusable(false);
        jCheckBoxRecordarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-Cancel.png"))); // NOI18N
        jCheckBoxRecordarSesion.setOpaque(false);
        jCheckBoxRecordarSesion.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-Check-Press.png"))); // NOI18N
        jCheckBoxRecordarSesion.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-Cancel-Rollover.png"))); // NOI18N
        jCheckBoxRecordarSesion.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-Check-Rollover.png"))); // NOI18N
        jCheckBoxRecordarSesion.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-Check.png"))); // NOI18N
        add(jCheckBoxRecordarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, -1, -1));

        jCheckBoxMantenerSesion.setFont(Ventana.font);
        jCheckBoxMantenerSesion.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxMantenerSesion.setText("Mantener sesion");
        jCheckBoxMantenerSesion.setBorder(null);
        jCheckBoxMantenerSesion.setFocusable(false);
        jCheckBoxMantenerSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-Cancel.png"))); // NOI18N
        jCheckBoxMantenerSesion.setOpaque(false);
        jCheckBoxMantenerSesion.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-Check-Press.png"))); // NOI18N
        jCheckBoxMantenerSesion.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-Cancel-Rollover.png"))); // NOI18N
        jCheckBoxMantenerSesion.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-Check-Rollover.png"))); // NOI18N
        jCheckBoxMantenerSesion.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-Check.png"))); // NOI18N
        add(jCheckBoxMantenerSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 650, -1, -1));

        jButtonRegister.setFont(Ventana.font);
        jButtonRegister.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-1.png"))); // NOI18N
        jButtonRegister.setText("REGISTER");
        jButtonRegister.setBorderPainted(false);
        jButtonRegister.setContentAreaFilled(false);
        jButtonRegister.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonRegister.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-1-Press.png"))); // NOI18N
        jButtonRegister.setRequestFocusEnabled(false);
        jButtonRegister.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-1-Rollover.png"))); // NOI18N
        jButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterActionPerformed(evt);
            }
        });
        add(jButtonRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 600, -1, -1));

        jButtonLogin.setFont(Ventana.font);
        jButtonLogin.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-1.png"))); // NOI18N
        jButtonLogin.setText("BACK");
        jButtonLogin.setBorderPainted(false);
        jButtonLogin.setContentAreaFilled(false);
        jButtonLogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonLogin.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-1-Press.png"))); // NOI18N
        jButtonLogin.setRequestFocusEnabled(false);
        jButtonLogin.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-1-Rollover.png"))); // NOI18N
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });
        add(jButtonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 600, -1, -1));

        jButtonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-Cancel.png"))); // NOI18N
        jButtonSalir.setBorderPainted(false);
        jButtonSalir.setContentAreaFilled(false);
        jButtonSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSalir.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-Cancel-Press.png"))); // NOI18N
        jButtonSalir.setRequestFocusEnabled(false);
        jButtonSalir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-Cancel-Rollover.png"))); // NOI18N
        add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 10, -1, -1));

        jLabelTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-ResidentUDO.png"))); // NOI18N
        jLabelTitulo.setToolTipText("");
        add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, -1, -1));

        jTextFieldUser.setFont(Ventana.font);
        jTextFieldUser.setForeground(new java.awt.Color(204, 204, 204));
        jTextFieldUser.setBorder(null);
        jTextFieldUser.setOpaque(false);
        jTextFieldUser.setSelectionColor(new java.awt.Color(255, 102, 0));
        add(jTextFieldUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 460, 240, 40));

        jLabelUser.setFont(Ventana.font);
        jLabelUser.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUser.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelUser.setText("Usuario");
        add(jLabelUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 470, 250, 30));

        jSeparator1.setForeground(new java.awt.Color(255, 102, 0));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 500, 240, 10));

        jTextFieldPass.setFont(Ventana.font);
        jTextFieldPass.setForeground(new java.awt.Color(204, 204, 204));
        jTextFieldPass.setBorder(null);
        jTextFieldPass.setOpaque(false);
        jTextFieldPass.setSelectionColor(new java.awt.Color(255, 102, 0));
        add(jTextFieldPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 530, 240, 40));

        jLabelPass.setFont(Ventana.font);
        jLabelPass.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPass.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelPass.setText("Contraseña");
        add(jLabelPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 540, 250, 30));

        jSeparator2.setForeground(new java.awt.Color(255, 102, 0));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 570, 240, 10));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Fondo-Opaco.png"))); // NOI18N
        jLabelFondo.setText("jLabel5");
        add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterActionPerformed
        // TODO add your handling code here:
        int resultado = Cargador.register(jTextFieldUser.getText(), jTextFieldPass.getText());
        switch (resultado) {
            case Cargador.USER_TOO_LONG:
                Opcion.showMessage(ventana, true, "Máximo " + Cargador.MAX_CARACTERES + " caracteres");
                break;
            case Cargador.USER_INVALID:
                Opcion.showMessage(ventana, true, "Usuario inválido");
                break;
            case Cargador.PASS_INVALID:
                Opcion.showMessage(ventana, true, "Contraseña no permitida");
                break;
            case Cargador.USER_EXIST:
                Opcion.showMessage(ventana, true, "Este usuario ya existe");
                break;
            case Cargador.USER_CREATED:
                Opcion.showMessage(ventana, true, "Usuario creado con éxito");
                ventana.cargarNuevoUsuario(jTextFieldUser.getText());
                ventana.guardarSesion(jTextFieldUser.getText(), jTextFieldPass.getText(), jCheckBoxMantenerSesion.isSelected(), jCheckBoxRecordarSesion.isSelected());
                ventana.setContentPane("Datos");
                break;
            default:
                Opcion.showMessage(ventana, true, "Error");
                break;
        }
    }//GEN-LAST:event_jButtonRegisterActionPerformed

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        // TODO add your handling code here:
        ventana.setContentPane("Login");
    }//GEN-LAST:event_jButtonLoginActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JButton jButtonRegister;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JCheckBox jCheckBoxMantenerSesion;
    private javax.swing.JCheckBox jCheckBoxRecordarSesion;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelPass;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelUser;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextFieldPass;
    private javax.swing.JTextField jTextFieldUser;
    // End of variables declaration//GEN-END:variables

}
