/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Juego.Vista.Estado;

import Juego.Vista.Ventana;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Lewis
 */
public class Tutorial extends javax.swing.JPanel {

    private int paso;
    /**
     * Creates new form Tutorial
     */
    public Tutorial(final Ventana ventana) {
        initComponents();
        setFocusable(false);
        setOpaque(false);
        setBounds(0, 0, ventana.getWidth(), ventana.getHeight());
        paso = 1;
        
        jButtonAnterior.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                if(paso > 1) {
                    paso--;
                }
                changeTextPaso();
            }
        });
        jButtonSiguiente.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                if(paso != 0) {
                    paso++;
                }
                changeTextPaso();
                
                if(paso == 0)
                    ventana.setContentPane("Juego");
            }
        });
        jButtonSaltar.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                paso = 0;
                ventana.setContentPane("Juego");
            }
        });
        
        jButtonX.setVisible(false);
        jButtonXL.setVisible(false);
    }
    
    @Override
    public void paint(Graphics g) {
        super.paint(g);
        //g.drawString(str, 50, 50);
    }
    
    public int getPaso() {
        return paso;
    }
    
    public void changeTextPaso(){
        jButtonW.setVisible(false);
        jButtonS.setVisible(false);
        jButtonA.setVisible(false);
        jButtonD.setVisible(false);
        jButtonX.setVisible(false);
        jButtonXL.setVisible(false);
        String str = "";
        switch(paso) {
            case 1:
                str = "Presiona las teclas A, W, S, D, para moverte";
                jButtonW.setVisible(true);
                jButtonS.setVisible(true);
                jButtonA.setVisible(true);
                jButtonD.setVisible(true);
                break;
            case 2:
                str = "Manten presionado shift para correr";
                jButtonXL.setText("Shift");
                jButtonXL.setVisible(true);
                break;
            case 3:
                str = "Presiona E para recoger los objetos y armas cercanas";
                jButtonX.setText("E");
                jButtonX.setVisible(true);
                break;
            case 4:
                str = "Presiona I para ver tus objetos de tu inventario";
                jButtonX.setText("I");
                jButtonX.setVisible(true);
                break;
            case 5:
                str = "Puedes ver tus armas y municiones en la siguientes secciones";
                break;
            case 6:
                str = "Puedes escoger cualquiera como atajo en los numeros de teclado";
                break;
            case 7:
                str = "Puedes escoger un arma de tu inventario presionando 'Portar'";
                jButtonXL.setText("Portar");
                jButtonXL.setVisible(true);
                break;
            case 8:
                str = "Puedes recargar tu arma presionando la tecla R o en 'Recargar'";
                jButtonX.setText("R");
                jButtonX.setVisible(true);
                break;
            case 9:
                str = "Cuando encuentres a un vendedor, presiona B para ver su tienda";
                jButtonX.setText("B");
                jButtonX.setVisible(true);
                break;
            case 10:
                str = "Haz click derecho sobre algo para ver que es";
                break;
            case 11:
                str = "Pulsa la tecla escape para pausar el juego";
                jButtonX.setText("ESC");
                jButtonX.setVisible(true);
                break;
            case 12:
                str = "Hay enemigos cerca! Presiona espacio para atacarlos y recoger sus articulos";
                break;
            default:
                paso = 0;
                break;
        }
        jTextAreaPaso.setText(str);
        jTextAreaPaso.setCaretPosition(0);

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonX = new javax.swing.JButton();
        jButtonXL = new javax.swing.JButton();
        jButtonA = new javax.swing.JButton();
        jButtonW = new javax.swing.JButton();
        jButtonS = new javax.swing.JButton();
        jButtonD = new javax.swing.JButton();
        jButtonAnterior = new javax.swing.JButton();
        jButtonSiguiente = new javax.swing.JButton();
        jButtonSaltar = new javax.swing.JButton();
        jScrollPaneHistoria = new javax.swing.JScrollPane();
        jTextAreaPaso = new javax.swing.JTextArea();
        jTextAreaPaso.setLineWrap(true);
        jTextAreaPaso.setWrapStyleWord(false);
        jTextAreaPaso.setEditable(false);
        jPanelOpaco = new javax.swing.JPanel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonX.setFont(Ventana.font);
        jButtonX.setForeground(new java.awt.Color(255, 255, 255));
        jButtonX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-2.png"))); // NOI18N
        jButtonX.setText("E");
        jButtonX.setBorderPainted(false);
        jButtonX.setContentAreaFilled(false);
        jButtonX.setFocusable(false);
        jButtonX.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonX.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-2-Press.png"))); // NOI18N
        jButtonX.setRequestFocusEnabled(false);
        jButtonX.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-2-Rollover.png"))); // NOI18N
        add(jButtonX, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 480, 100, -1));

        jButtonXL.setFont(Ventana.font);
        jButtonXL.setForeground(new java.awt.Color(255, 255, 255));
        jButtonXL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-1.png"))); // NOI18N
        jButtonXL.setText("E");
        jButtonXL.setBorderPainted(false);
        jButtonXL.setContentAreaFilled(false);
        jButtonXL.setFocusable(false);
        jButtonXL.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonXL.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-1-Press.png"))); // NOI18N
        jButtonXL.setRequestFocusEnabled(false);
        jButtonXL.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-1-Rollover.png"))); // NOI18N
        add(jButtonXL, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 490, -1, -1));

        jButtonA.setFont(Ventana.font);
        jButtonA.setForeground(new java.awt.Color(255, 255, 255));
        jButtonA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-2.png"))); // NOI18N
        jButtonA.setText("A");
        jButtonA.setBorderPainted(false);
        jButtonA.setContentAreaFilled(false);
        jButtonA.setFocusable(false);
        jButtonA.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonA.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-2-Press.png"))); // NOI18N
        jButtonA.setRequestFocusEnabled(false);
        jButtonA.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-2-Rollover.png"))); // NOI18N
        add(jButtonA, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 100, -1));

        jButtonW.setFont(Ventana.font);
        jButtonW.setForeground(new java.awt.Color(255, 255, 255));
        jButtonW.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-2.png"))); // NOI18N
        jButtonW.setText("W");
        jButtonW.setBorderPainted(false);
        jButtonW.setContentAreaFilled(false);
        jButtonW.setFocusable(false);
        jButtonW.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonW.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-2-Press.png"))); // NOI18N
        jButtonW.setRequestFocusEnabled(false);
        jButtonW.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-2-Rollover.png"))); // NOI18N
        add(jButtonW, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 100, -1));

        jButtonS.setFont(Ventana.font);
        jButtonS.setForeground(new java.awt.Color(255, 255, 255));
        jButtonS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-2.png"))); // NOI18N
        jButtonS.setText("S");
        jButtonS.setBorderPainted(false);
        jButtonS.setContentAreaFilled(false);
        jButtonS.setFocusable(false);
        jButtonS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonS.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-2-Press.png"))); // NOI18N
        jButtonS.setRequestFocusEnabled(false);
        jButtonS.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-2-Rollover.png"))); // NOI18N
        add(jButtonS, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 480, 100, -1));

        jButtonD.setFont(Ventana.font);
        jButtonD.setForeground(new java.awt.Color(255, 255, 255));
        jButtonD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-2.png"))); // NOI18N
        jButtonD.setText("D");
        jButtonD.setBorderPainted(false);
        jButtonD.setContentAreaFilled(false);
        jButtonD.setFocusable(false);
        jButtonD.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonD.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-2-Press.png"))); // NOI18N
        jButtonD.setRequestFocusEnabled(false);
        jButtonD.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-2-Rollover.png"))); // NOI18N
        add(jButtonD, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 480, 100, -1));

        jButtonAnterior.setFont(Ventana.font);
        jButtonAnterior.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-Prev.png"))); // NOI18N
        jButtonAnterior.setBorderPainted(false);
        jButtonAnterior.setContentAreaFilled(false);
        jButtonAnterior.setFocusable(false);
        jButtonAnterior.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAnterior.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-Prev-Press.png"))); // NOI18N
        jButtonAnterior.setRequestFocusEnabled(false);
        jButtonAnterior.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-Prev-Rollover.png"))); // NOI18N
        add(jButtonAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 640, -1, -1));

        jButtonSiguiente.setFont(Ventana.font);
        jButtonSiguiente.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-Next.png"))); // NOI18N
        jButtonSiguiente.setBorderPainted(false);
        jButtonSiguiente.setContentAreaFilled(false);
        jButtonSiguiente.setFocusable(false);
        jButtonSiguiente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSiguiente.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-Next-Press.png"))); // NOI18N
        jButtonSiguiente.setRequestFocusEnabled(false);
        jButtonSiguiente.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-Next-Rollover.png"))); // NOI18N
        add(jButtonSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 640, -1, -1));

        jButtonSaltar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSaltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-Skip.png"))); // NOI18N
        jButtonSaltar.setBorderPainted(false);
        jButtonSaltar.setContentAreaFilled(false);
        jButtonSaltar.setFocusable(false);
        jButtonSaltar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSaltar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-Skip-Press.png"))); // NOI18N
        jButtonSaltar.setRequestFocusEnabled(false);
        jButtonSaltar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/Btn-Skip-Rollover.png"))); // NOI18N
        add(jButtonSaltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 10, -1, -1));

        jScrollPaneHistoria.setBorder(null);
        jScrollPaneHistoria.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPaneHistoria.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPaneHistoria.setOpaque(false);

        jTextAreaPaso.setEditable(false);
        jTextAreaPaso.setColumns(20);
        jTextAreaPaso.setFont(Ventana.font);
        jTextAreaPaso.setForeground(new java.awt.Color(255, 255, 255));
        jTextAreaPaso.setLineWrap(true);
        jTextAreaPaso.setRows(5);
        jTextAreaPaso.setText("Presiona las teclas A, W, S, D para moverte");
        jTextAreaPaso.setWrapStyleWord(true);
        jTextAreaPaso.setBorder(null);
        jTextAreaPaso.setOpaque(false);
        jScrollPaneHistoria.setViewportView(jTextAreaPaso);
        jScrollPaneHistoria.getViewport().setOpaque(false);

        add(jScrollPaneHistoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, 510, 120));

        jPanelOpaco.setBackground(new Color(0, 0, 0, 150));
        add(jPanelOpaco, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonA;
    private javax.swing.JButton jButtonAnterior;
    private javax.swing.JButton jButtonD;
    private javax.swing.JButton jButtonS;
    private javax.swing.JButton jButtonSaltar;
    private javax.swing.JButton jButtonSiguiente;
    private javax.swing.JButton jButtonW;
    private javax.swing.JButton jButtonX;
    private javax.swing.JButton jButtonXL;
    private javax.swing.JPanel jPanelOpaco;
    private javax.swing.JScrollPane jScrollPaneHistoria;
    private javax.swing.JTextArea jTextAreaPaso;
    // End of variables declaration//GEN-END:variables
}
